spring.application.name=AtlasPay Secure Gateway

#PostgresSQL Configuration
spring.datasource.url = dbc:postgresql://localhost:5432/atlaSpay_db
spring.datasource.username = postgres
spring.datasource.password = Meetu@12522
spring.datasource.driver-class-name =org.postgresql.Driver

#JPA configuration
spring.jpa.database-platform =org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=auto
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

#Server configuration
server.port = 8080
sesrver.servlet.contex-path=/api

#JWT Configuration
jwt.secret.key=01507d551d9405300d66c94597699291086efa5ab3e54e304fa39f7f74e2b5be
jwt.expiration.time=86400000


#Application Configuration
spring.profiles.active=dev